Remove every instance of the COMMAND macro
project-imprimis/libprimis pull request #246
Opened 2022-04-23 17:44 UTC by Duskhorn

2022-04-23 17:53 UTC, no-lex requested changes
Just one tiny issue with trailing whitespace here.

2022-04-23 17:53 UTC, no-lex commented on src/engine/interface/menus.cpp
> +namespace
trailing whitespace here

2022-04-23 18:43 UTC, Duskhorn commented
Did I really make a stupid typo in the meantime? I'm so bad lol

2022-04-24 04:55 UTC, no-lex approved these changes

2022-04-24 04:56 UTC, merged