std::map and std::unordered_map STL #257
project-imprimis/libprimis pull request #258
Opened 2022-09-05 09:53 UTC by Duskhorn

I'll add this just to keep track for now, rn I have some painful template errors and I don't understand what it wants from me

2022-09-07 13:17 UTC, Duskhorn commented
I require help in this template error landscape
```
In file included from /usr/include/c++/10.2/string:48,
                 from /home/dusk/projects/libprimis/src/engine/../libprimis-headers/cube.h:27,
                 from /home/dusk/projects/libprimis/src/engine/model/animmodel.cpp:10:
/usr/include/c++/10.2/bits/stl_function.h: In instantiation of 'constexpr bool std::less<_Tp>::operator()(const _Tp&, const _Tp&) const [with _Tp = animmodel::shaderparams]':
/usr/include/c++/10.2/bits/stl_map.h:499:32:   required from 'std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = animmodel::shaderparams; _Tp = animmodel::ShaderParamsKey; _Compare = std::less<animmodel::shaderparams>; _Alloc = std::allocator<std::pair<const animmodel::shaderparams, animmodel::ShaderParamsKey> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = animmodel::ShaderParamsKey; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = animmodel::shaderparams]'
/home/dusk/projects/libprimis/src/engine/model/animmodel.cpp:204:39:   required from here
/usr/include/c++/10.2/bits/stl_function.h:386:20: error: no match for 'operator<' (operand types are 'const animmodel::shaderparams' and 'const animmodel::shaderparams')
  386 |       { return __x < __y; }
      |                ~~~~^~~~~
```

2022-09-08 20:42 UTC, no-lex requested changes

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/rendermodel.cpp
> +    model **mm = &models[name];
These two operations do not have the same semantics. `hashnameset::access` either finds and returns the pointer to the data associated with `name` or nullptr; `operator[]` either finds the data associated with `name`  or default initializes a new object.

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/rendertext.cpp
> +    return &fonts[name];
may return an empty object, see above comment on `operator[]` vs `access`

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/shader.cpp
> +    GlobalShaderParamState *param = &globalparams[name];
may point to an empty object

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/shader.cpp
> +    GlobalShaderParamState *param = &globalparams[name];
may point to an empty object

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/shader.cpp
> +    Shader *exists = &shaders[name];
may point to an empty object

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/shader.cpp
> +    Shader *s = &shaders[name];
may point to an empty object

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/shader.cpp
>      if(!s)
this guard doesn't make sense because you will always point to a member of `shaders`

2022-09-08 20:42 UTC, no-lex commented on src/engine/interface/ui.cpp
> +            auto [key, window] = *search; // I may have broken this, remove this comment if engine compiles/works. Issue #257
use `first` and `second` when dealing with dereferenced iterators inside associative containers (`std::map`/`unordered_map` objects are stored as `std::pair`)

2022-09-08 20:42 UTC, no-lex commented on src/engine/model/animmodel.cpp
> +bool operator==(const animmodel::shaderparams& lhs, const animmodel::shaderparams& rhs)
`htcmp/hthash` are just the names of the operators that std:: associative containers want; you can just rename `htcmp` to `operator==` instead of an extra layer of indirection

2022-09-08 20:42 UTC, no-lex commented on src/engine/model/animmodel.h
> +struct std::hash<animmodel::shaderparams>
you can just rename `hthash` to this std::hash specialization instead of wrapping it

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/rendermodel.cpp
> +    if(!name || !name[0] || models.find(name) == models.end() || std::find(preloadmodels.begin(), preloadmodels.end(), name) != preloadmodels.end() )
i think you want to see if `models.find(name) != models.end()`

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/shader.cpp
> +    Shader *s = &shaders[name];
may return an empty object

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/shader.cpp
> +    localparams.insert_or_assign(name, localparams.size());
insert_or_assign isn't really necessary here, `access(const char *, T)` is equivalent to operator `[]`; `insert_or_assign` will overwrite (assign) if the specified key already exists while `access` does not (only assigns if no key found)

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/shader.cpp
> +    for(auto &[k, g] : globalparams) { g.version = ++nextversion; }
since this isn't a macro you should put { and } on their own lines like any other for loop

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/rendermodel.cpp
> +    for(auto &[k, m] : models) { delete m; }
should have { } on their own lines like any other for loop (no longer a macro)

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/rendermodel.cpp
> +    for(auto &[k, m] : models) { m->cleanup(); }
should have { } on their own lines like any other for loop (no longer a macro)

2022-09-08 20:42 UTC, no-lex commented on src/engine/interface/console.cpp
> +    KeyM *km = &keyms[code];
may create an empty object, see below comment on `access` vs `operator[]`

2022-09-08 20:42 UTC, no-lex commented on src/engine/interface/console.cpp
> +    for(auto &[k, km] : keyms) { binds.push_back(&km); }
should have { } on their own lines like any other for loop (no longer a macro)

2022-09-08 20:42 UTC, no-lex commented on src/engine/interface/console.cpp
> +        for(auto &[k, km] : keyms) { km.clear(KeyM::Action_Default); }
should have { } on their own lines like any other for loop (no longer a macro)

2022-09-08 20:42 UTC, no-lex commented on src/engine/interface/console.cpp
> +        for(auto &[k, km] : keyms) { km.clear(KeyM::Action_Spectator); }
should have { } on their own lines like any other for loop (no longer a macro)

2022-09-08 20:42 UTC, no-lex commented on src/engine/interface/console.cpp
> +        for(auto &[k, km] : keyms) { km.clear(KeyM::Action_Editing); }
should have { } on their own lines like any other for loop (no longer a macro)

2022-09-08 20:42 UTC, no-lex commented on src/engine/interface/console.cpp
> +       for(auto &[k, km] : keyms) { km.clear(); }
should have { } on their own lines like any other for loop (no longer a macro)

2022-09-08 20:42 UTC, no-lex commented on src/engine/interface/ui.cpp
> +        for(auto &[k, w] : windows) { delete w; }
should have { } on their own lines like any other for loop (no longer a macro)

2022-09-08 20:42 UTC, no-lex commented on src/engine/model/animmodel.cpp
> +        for(auto& [k, key] : keys) { key.version = -1; }
should have { } on their own lines like any other for loop (no longer a macro)

2022-09-08 20:42 UTC, no-lex commented on src/engine/render/rendermodel.cpp
> +        models.insert_or_assign(m->name, m);
see below comment on `insert_or_assign` vs `access`

2022-09-14 08:20 UTC, Duskhorn commented on src/engine/model/animmodel.cpp
> +bool operator==(const animmodel::shaderparams& lhs, const animmodel::shaderparams& rhs)
doesn't this break every use of this particular overload for htcmp in the engine?
I was gonna save the change you proposed for a later commit/PR

2022-09-14 08:35 UTC, Duskhorn commented on src/engine/interface/ui.cpp
> +            auto [key, window] = *search; // I may have broken this, remove this comment if engine compiles/works. Issue #257
So no pair destructuring at all?

2023-02-13 10:28 UTC, Duskhorn commented on src/engine/render/rendermodel.cpp
> +    model **mm = &models[name];
`
auto mm = models.find(name);
    model *m;
    if(mm != models.end())
    {
        m = mm->second;
    }
`
Is this the right way to go?

2023-02-13 21:22 UTC, no-lex commented on src/engine/render/rendermodel.cpp
> +    model **mm = &models[name];
Yes, that should work. `find()` and `access()` should do the same thing in this case.

2023-03-01 14:55 UTC, Duskhorn commented
Given the fact that a lot has happened since I last worked on this and I can't keep track of the stuff to fix I'm gonna close this PR in favor of a newer one

2023-03-01 14:55 UTC, closed without merging